# Generated by Django 3.2.4 on 2021-09-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersorter', '0003_result_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='user',
        ),
    ]
